# Generated by Django 5.1 on 2024-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("park_name", models.CharField(max_length=255)),
                ("location_name", models.CharField(max_length=255)),
                ("park_type_id", models.CharField(max_length=255)),
                ("park_type_desc", models.CharField(max_length=255)),
                ("capacity_of_park", models.IntegerField()),
                ("working_time", models.CharField(max_length=255)),
                ("county_name", models.CharField(max_length=255)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
        ),
    ]
