# Generated by Django 5.1 on 2024-08-29 12:21

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parkapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspot",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
            ),
        ),
    ]
