# Generated by Django 5.1 on 2024-08-29 12:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parkapp", "0002_parkingspot_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspot",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
