# Generated by Django 5.1 on 2024-08-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0003_alter_parkingspot_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='latitude',
            new_name='LATITUDE',
        ),
        migrations.RenameField(
            model_name='parkingspot',
            old_name='longitude',
            new_name='LONGITUDE',
        ),
    ]
